<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tm_masterslave"
 *
 * Auto generated by Extension Builder 2018-05-02
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Toumoro master slave database tm_masterslave',
    'description' => 'WraperClass for doctrine MasterSlaveConnection',
    'category' => 'plugin',
    'author' => 'Toumoro',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '9.5'
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
